name: AntiAFK
version: 1.0.4
main: com.bentahsin.antiafk.AntiAFKPlugin
api-version: '1.13'
author: bentahsin
description: Oyuncuların sunucuda AFK kalmasını engeller ve özelleştirilebilir aksiyonlar uygular.
load: POSTWORLD
softdepend: [ProtocolLib, PlaceholderAPI, WorldGuard, Geyser-Spigot, Floodgate]